# config
description: "心之所向，无惧无悔,<br>愿求仁得仁，复无怨怼！"

# comment system
valine: ## https://valine.js.org
  enable: true ## If you want to use Valine comment system, please set the value to true.
  appid:  ## Your LeanCloud application App ID, e.g. pRBBL2JR4N7kLEGojrF0MsSs-gzGzoHsz
          ## [Optional] You can set valine.appid on your blog source _config.yml
  appkey: ## Your LeanCloud application App Key, e.g. tjczHpDfhjYDSYddzymYK1JJ
          ## [Optional] You can set valine.appkey on your blog source _config.yml
  lang: zh-cn ## Language, e.g. zh-cn, en
  notify: false ## Mail notifier, see https://github.com/xCss/Valine/wiki/Valine-评论系统中的邮件提醒设置
  verify: false ## Validation code.
  placeholder: "ヾﾉ≧∀≦)o Come on, say something..." ## Comment box placeholders.
  avatar: 'identicon' ## Gravatar type, see https://github.com/xCss/Valine/wiki/avatar-setting-for-valine
  pageSize: 10 ## Number of comments per page.
  guest_info: nick,mail,link ## Attributes of reviewers.

# baidu 
baidu: ## https://tongji.baidu.com, https://ziyuan.baidu.com
  analytics: true
  analytics_id: ## Your baidu tongji related id, e.g. 213250b3059d3a7c6607d30bea630c32
                ## [Optional] You can set baidu.analytics_id on your blog source _config.yml
  verification: ## Your baidu ziyuan verification code
                ## [Optional] You can set baidu.verification on your blog source _config.yml

busuanzi: true  ## If you want show counter of views, please set the value to true
local_search: true
customize_css: false  ## if enable customize_css, it will load file source/css/customize.scss
fancybox: true  ## for image view
copyright: true ## for CC BY-NC 4.0 license

menu:
  - page: 归档
    directory: archives/
  - page: 分类
    directory: categories/
  - page: 标签
    directory: tags/
  - page: 关于
    directory: about/
  - page: rss
    directory: atom.xml

icons:
  date: fa fa-calendar
  category: fa fa-folder
  tag: fa fa-tag
  tags: fa fa-tags
  view: fa fa-eye
  visitor: fa fa-user

widgets: ## Six widgets in sidebar provided: search, category, tag, recent_posts, rencent_comments and links.
  #- search
  #- category
  #- tag
  #- recent_posts
  #- recent_comments
  #- links

links:
  - title: friend-1
    url: https://www.friend-1.com

# Static files
js: js
css: css
plugins: plugins

# Theme version
version: 0.0.1
